print ("Curiculum vitae")
print ("nume- Iatemirschi")
print ("prenume- Vlad")
print ("nascut- 15 iunie 2004")
print ("starea civila- celibatar")
print ("studii- primare,gimnaziale,liceale incomplete")
print ("IPLT M. Eminescu")
print ("specialitate- elev")
print ("succese- Locul 3 la olimpiada de limba romana cl.8; participant la actiuni de voluntariat")
print ("cunoasterea limbilor- limba engleza; limba germana; limba romana")
print ("interese- domeniul IT; jocuri video; fotbal; ghitara; aviatia")
print ("adresa- orasul Balti, str.Pavel Botu 87")
print ("telefon contact- 69088684")
print ("E-mail- vladiatemir@gmail.com")